services:
  auth-db:
    image: postgres:16
    container_name: investwise-postgres
    restart: always
    environment:
      POSTGRES_DB: InvestWiseDB
      POSTGRES_USER: investmaster
      POSTGRES_PASSWORD: Abhiji@99
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
  
  redis:
    image: redis:latest
    container_name: investwise-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge